POC = 0
FAST = 1
NORMAL = 2
FAST_PARANOIAC = 3
PARANOIAC = 4
ANOMALIES = 5
CLUSTERING = 6
BEST = 0
BEST_3 = 1
EACH_BEST = 2
ALL = 3
DTYPES = ['int', 'float', 'int16', 'int32', 'int64', 'float16', 'float32', 'float64']
FTYPES = ['float', 'float16', 'float32', 'float64']
ITYPES = ['int', 'int16', 'int32', 'int64']
METRICS_TYPES = ['accuracy', 'test_accuracy', 'combined', 'rmse', 'cdistance']
ACCURACY_METRICS = ['accuracy', 'test_accuracy', 'combined']
REGRESSION_METRICS = ['rmse']
CLUSTERING_METRICS = ['cdistance']
NO_STANDARDIZE = ['H2ORandomForestEstimator', 'H2OGradientBoostingEstimator', '']